name: CI

on:
  pull_request:
    branches: [ main ]
    paths-ignore:
      - "docs/**"
      - "README.md"
  push:
    branches: [ main ]
    paths-ignore:
      - "docs/**"
      - "README.md"

env:
  POETRY_VERSION: "1.3.2"

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.10" ]
    
    steps:
    # ---------------------------------------------
    # -----           gather repo             -----
    # ---------------------------------------------
    - uses: actions/checkout@v3

    # ---------------------------------------------
    # -----      setup and cache python       -----
    # ---------------------------------------------
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Cache poetry
      id: cache-poetry
      uses: actions/cache@v3
      with:
        path: ~/.local
        key: poetry-${{ runner.os }}-${{ matrix.python-version }}-${{ env.POETRY_VERSION }}

    - name: Install poetry
      if: steps.cache-poetry.outputs.cache-hit != 'true'
      uses: snok/install-poetry@v1
      with:
        version: ${{ env.POETRY_VERSION }}
        virtualenvs-in-project: true

    - name: Cache venv
      id: cache-venv
      uses: actions/cache@v3
      with:
        path: .venv
        key: venv-${{ runner.os }}-${{ matrix.python-version }}-${{ env.POETRY_VERSION }}-${{ hashFiles('poetry.lock') }}
        restore-keys: |
          venv-${{ runner.os }}-${{ matrix.python-version }}-${{ env.POETRY_VERSION }}-

    - name: Install dependencies
      if: steps.cache-venv.outputs.cache-hit != 'true'
      run: poetry install --all-extras


    # ---------------------------------------------
    # -----           Lint and Test           -----
    # ---------------------------------------------
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        poetry run flake8 subgrounds --count --select=E9,F63,F7,F82 --show-source --statistics

        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        poetry run flake8 subgrounds --count --exit-zero --max-complexity=10 --max-line-length=127 --indent-size=2 --statistics

    - name: Run unit tests
      run: poetry run pytest

    - name: Run examples smoke tests
      shell: bash
      run: sh tests/test_examples.sh

    # # ---------------------------------------------
    # # -----          Release Package          -----
    # # ---------------------------------------------
    # - name: Release
    #   if: |
    #     github.repository == '0xPlaygrounds/subgrounds'
    #     && github.event_name == 'push'
    #     && github.ref == 'refs/heads/main'
    #   env:
    #     GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #     PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
    #   run: |
    #     git config --global user.name "github-actions"
    #     git config --global user.email "action@github.com"
    #     poetry run semantic-release publish -v DEBUG -D commit_author="github-actions <action@github.com>"
